name: module3_task0
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 15 * * *'

jobs:
  runs-on: ubuntu:18.04
  steps:
    - name: Clone the repo
      uses: actions/checkout@v3
    - name: Cd in the correct directory and make help
      run: |
        cd ${{ github.workflow }}
        make help
