name: module3_task0
run-name: module3_task0
on:
  schedule:
    - cron: "0 15 * * *"
  push:
jobs:
  first_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: Cd in the correct directory and make help
        run: |
          cd module3_task0
          make help
