name: module3_task1
run-name: module3_task1
on:
  schedule:
    - cron: "0 15 * * *"
  push:
jobs:
  first_job:
    defaults:
      run:
        working-directory: ./${{ github.workflow }}
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: install missing tools for building
        run: ./setup.sh
      - name: Build the hugo website via the target build.
        run: make build
